### ISSUE TITLE
npm module "promise" version 7.0.3 is broken

### ISSUE THREAD

**Issue by yelled3** [pqx/bloodhound#1]
when switching to `"promise": "^6.0.1"` - it works like a charm

base on:
https://github.com/eclipsesource/tabris-js/issues/540

**Comment by wangzuo** [comment]
There are still some issues with this package, may be [es6-promise](https://github.com/jakearchibald/es6-promise) instead?

**Comment by yelled3** [comment]
@wangzuo my fork works just fine:
https://github.com/yelled3/node-bloodhound/blob/master/package.json#L14

that being said, whatever lib works best :-)

maybe https://github.com/petkaantonov/bluebird ?
