### ISSUE TITLE
Including this package clears localStorage?

### ISSUE THREAD

**Issue by alexhopeoconnor** [pqx/bloodhound#7]
Hello,

I am developing an application using webpack and for some reason including this package clears data from the localStorage object?
`var Bloodhound = require("bloodhound-js");`

Not sure what is going on at all, I was until recently just including the scripts from the publisher and have been switching to using npm packages, this is a tidy way to include bloodhound but unfortunately breaks my application.

Thanks heaps for even taking the time to develop the package though.

**Comment by affemaen** [comment]
Seems to be the included package storage2 that causes the problem.

https://github.com/pqx/storage2
